export const ROUTES = {
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  DASHBOARD: '/dashboard',
  ACCOUNT: '/account',
  ACCOUNTS: '/accounts',
  TRANSFER: '/transfer',
  DEPOSIT: '/deposit',
  TRANSACTIONS: '/transactions',
  NEWS: '/news',
  NEWS_DETAIL: '/news/:id',
  NEWS_ADMIN: '/news/admin',
  NEWS_ADMIN_CREATE: '/news/admin/create',
  NEWS_ADMIN_EDIT: '/news/admin/edit/:id',
  ADMIN_USERS: '/admin/users',
  ADMIN_ROLES: '/admin/roles',
  ADMIN_PERMISSIONS: '/admin/permissions',
  FORBIDDEN: '/403',
  NOT_FOUND: '*',
  HOME: '/',
  SETTINGS: '/settings',
} as const;
